/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreeRecipesRouteImport } from './routes/free-recipes'
import { Route as CookbooksIndexRouteImport } from './routes/cookbooks.index'
import { Route as CookbooksHandleRouteImport } from './routes/cookbooks.$handle'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRecipesRoute = FreeRecipesRouteImport.update({
  id: '/free-recipes',
  path: '/free-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksIndexRoute = CookbooksIndexRouteImport.update({
  id: '/cookbooks/',
  path: '/cookbooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksHandleRoute = CookbooksHandleRouteImport.update({
  id: '/cookbooks/$handle',
  path: '/cookbooks/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/cookbooks/$handle': typeof CookbooksHandleRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/cookbooks/': typeof CookbooksIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/cookbooks/$handle': typeof CookbooksHandleRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/cookbooks': typeof CookbooksIndexRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free-recipes': typeof FreeRecipesRoute
  '/cookbooks/$handle': typeof CookbooksHandleRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/cookbooks/': typeof CookbooksIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/free-recipes'
    | '/cookbooks/$handle'
    | '/recipes/$slug'
    | '/cookbooks/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/free-recipes'
    | '/cookbooks/$handle'
    | '/recipes/$slug'
    | '/cookbooks'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/free-recipes'
    | '/cookbooks/$handle'
    | '/recipes/$slug'
    | '/cookbooks/'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeRecipesRoute: typeof FreeRecipesRoute
  CookbooksHandleRoute: typeof CookbooksHandleRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  CookbooksIndexRoute: typeof CookbooksIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-recipes': {
      id: '/free-recipes'
      path: '/free-recipes'
      fullPath: '/free-recipes'
      preLoaderRoute: typeof FreeRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks/': {
      id: '/cookbooks/'
      path: '/cookbooks'
      fullPath: '/cookbooks/'
      preLoaderRoute: typeof CookbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks/$handle': {
      id: '/cookbooks/$handle'
      path: '/cookbooks/$handle'
      fullPath: '/cookbooks/$handle'
      preLoaderRoute: typeof CookbooksHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeRecipesRoute: FreeRecipesRoute,
  CookbooksHandleRoute: CookbooksHandleRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  CookbooksIndexRoute: CookbooksIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
